# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-31 18:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0028_auto_20180517_0727'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collecteddata',
            options={'ordering': ('indicator', 'date_collected'), 'verbose_name_plural': 'Indicator Output/Outcome Collected Data'},
        ),
        migrations.AlterModelOptions(
            name='level',
            options={'ordering': ('customsort',), 'verbose_name': 'Level'},
        ),
    ]
